config/routes.rb
Rails.application.routes.draw do

  get 'relationships/follow_user'

  get 'relationships/unfollow_user'

  get 'profiles/show'

	devise_for :users, :controllers => { registrations: 'registrations' }
	root 'posts#index'

  resources :posts do  
    resources :comments
    member do
      get 'like'
    end
  end  
  
  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile  

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: 'follower_id', class_name: 'User'
  belongs_to :following, foreign_key: 'following_id', class_name: 'User'
end 

app/models/post.rb
class Post < ApplicationRecord
	acts_as_votable

	validates :user_id, presence: true
	validates :image, presence: true
	validates :caption, length: { minimum: 3, maximum: 300 }
	
	has_many :comments, dependent: :destroy
	belongs_to :user

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	scope :of_followed_users, -> (following_users) { where user_id: following_users }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
 				 :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy 
  has_many :comments, dependent: :destroy
  
  has_attached_file :avatar, styles: { medium: '152x152#' }  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/  

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }  

  has_many :follower_relationships, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationships, source: :follower

  has_many :following_relationships, foreign_key: :follower_id, class_name: 'Follow'
  has_many :following, through: :following_relationships, source: :following

  def follow(user_id)  
    following_relationships.create(following_id: user_id)
  end

  def unfollow(user_id)
    following_relationships.find_by(following_id: user_id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

  def create  
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "Check the comment form, something went horribly wrong."
      render root_path
    end
  end

  def destroy  
    @comment = @post.comments.find(params[:id])

    @comment.destroy
    flash[:success] = "Comment deleted :("
    redirect_to root_path
  end  

  private

  def comment_params  
    params.require(:comment).permit(:content)
  end

  def set_post  
    @post = Post.find(params[:post_id])
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :owned_post, only: [:edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]


  # GET /posts
  # GET /posts.json
  def index  
    @posts = Post.all.order('created_at DESC')
  end 

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    flash[:success] = "Post deleted!"
    redirect_to root_path
  end

  def like  
    if @post.liked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:caption, :image)
    end

    def owned_post  
      unless current_user == @post.user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end  
  end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

	before_action :authenticate_user!
	before_action :owned_profile, only: [:edit, :update]
	before_action :set_user

	def show  
		@posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
	end  

	def edit  

	end 

	def update  
		if @user.update(profile_params)
			flash[:success] = 'Your profile has been updated.'
			redirect_to profile_path(@user.user_name)
		else
			@user.errors.full_messages
			flash[:error] = @user.errors.full_messages
			render :edit
		end
	end

	private

	def profile_params  
		params.require(:user).permit(:avatar, :bio)
	end  

	def owned_profile  
		unless current_user == @user
			flash[:alert] = "That profile doesn't belong to you!"
			redirect_to root_path
		end
	end

	def set_user  
		@user = User.find_by(user_name: params[:user_name])
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end  

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def follow_user
		@user = User.find_by! user_name: params[:user_name]
		if current_user.follow @user.id
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		end
	end

	def unfollow_user
		@user = User.find_by! user_name: params[:user_name]
		if current_user.unfollow @user.id
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def alert_for(flash_type)  
		{ success: 'alert-success',
			error: 'alert-danger',
			alert: 'alert-warning',
			notice: 'alert-info'
			}[flash_type.to_sym] || flash_type.to_s
		end 

		def profile_avatar_select(user)  
			return image_tag user.avatar.url(:medium),
			id: 'image-preview',
			class: 'img-responsive img-circle profile-image' if user.avatar.exists?
				image_tag 'default-avatar.jpg', id: 'image-preview',
				class: 'img-responsive img-circle profile-image'
		end  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	def likers_of(post)
		votes = post.votes_for.up.by_type(User)
		user_names = []
		unless votes.blank?
			votes.voters.each do |voter|
				user_names.push(link_to voter.user_name,
					profile_path(voter.user_name),
					class: 'user-name')
				end
				user_names.to_sentence.html_safe + like_plural(votes)
			end
		end

		private

		def like_plural(votes)
			return ' like this' if votes.count > 1
			' likes this'
		end
	end

app/helpers/profiles_helper.rb
module ProfilesHelper
	def current_user_is_following(current_user_id, followed_user_id)
		relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
		return true if relationship
	end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/layouts/_navbar.html.erb
	<nav class="navbar navbar-default">
		<div class="navbar-container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<div class="navbar-brand">
					<%= link_to "Instagram", root_path %>
				</div>
			</div>
			<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
					<li>
						<p class="navbar-text">	Hello, <%= current_user.user_name %></p>
					</li>
					<li>
						<%= link_to "New Post", new_post_path %>
					</li>
					<li>
						<%= link_to "Logout", destroy_user_session_path, method: :delete %>
					</li>
					<% else %>
					<li>
						<%= link_to "Login", new_user_session_path %>
					</li>
					<li>
						<%= link_to "Register", new_user_registration_path %>
					</li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>InstaApp</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
		<% end %>
	<%= render 'layouts/navbar' %>

	<%= yield %>
	</div>

</body>
</html>

app/views/posts/_form.html.erb
<div class="text-center">
	<%= image_tag @post.image.url(:medium) %>
</div>
<div class="from-wrapper">
	<%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
	<div class="form-group text-center">
		<%= f.input :image %>
	</div>
	<div class="form-group text-center">
		<%= f.input :caption %>
	</div>
	<div class="form-group text-center">
		<%= f.button :submit, class: 'btn-success' %>
	</div>
	<% end %>
</div>

app/views/posts/_likes.html.erb
<div class="likes">
	<%= likers_of post %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper row">
	<div class="post">
		<div class="post-head">
			<div class="thumb-img"></div>
			<div class="user-name">
				<%= post.user.user_name %>
			</div>
		</div>
		<div class="image center-block">
			<%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
		</div>
		<div class="post-bottom">
			<%= render 'posts/likes', post: post %>
			<div class="caption">
				<div class="caption-content">
					<div class="user-name">
						<%= link_to post.user.user_name, profile_path(post.user.user_name) %>
					</div>
					<%= post.caption %>
				</div>

			</div>
			<% if post.comments %>
				<% post.comments.each do |comment| %>
					<div class="comment">
						<div class="user-name">
							<%= comment.user.user_name %>
						</div>
						
						</div>
						<div class="comment-content">
							<%= comment.content %>
						</div>
						<% if comment.user == current_user %>
						<%= link_to  post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %> <span class="glyphicon glyphicon-remove delete-comment"></span>
					<% end %>
				<% end %>
			</div>
			<% end %>
			<% end %>
		</div>
				<div class="comment-like-form row">
							<div class="col-sm-1">
								<%= link_to '', like_post_path(post.id), remote: true,
                                              id: "like_#{post.id}",
                                              class: "glyphicon glyphicon-heart-empty" %>
				</div>
			<div class="comment-form col-sm-11">
				<%= form_for [post, post.comments.build] do |f| %>
				<%= f.text_field :content, placeholder: 'Add a comment!' %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<div class="text-center edit-links">
	<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="posts-wrapper row">
	<% @posts.each do |post| %>
	<%= render 'post', post: post %>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'post', post: @post %>

<% if @post.user.id == current_user.id %>
	<div class="text-center edit-links">
		<%= link_to 'Edit', edit_post_path(@post) %> |
		<%= link_to 'Back', posts_path %>
	</div>
<% else %>
	<div class="text-center edit-links">
		<%= link_to 'Back', posts_path %>	
	</div>
<% end %>

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
	<div class="post">
		<div class="post-body">
			<div class="image-wrap">
				<%= form_for @user, url: {action: "update"}, html: {multipart: true} do |f| %>
					<div class="row">
						<div class="col-md-12">
							<div class="form-group text-center">
								<h4>Change yout profile image</h4>
								<div class="img-circle">
									<%= profile_avatar_select(@user) %>
								</div>
								<%= f.file_field :avatar, onChange: 'loadFile(event)' %>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="form-group text-center">
								<h4>Update yout bio</h4>
								<%= f.text_area :bio, label: false, rows:4 %>
							</div>
						</div>
					</div>
					<div class="form-group text-center">
						<%= f.submit 'Update Profile', class: 'btn btn-success' %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/profiles/follow_user.js.erb
$('#follow-button').attr('class', 'btn unfollow-button')
                   .text('Following')
                   .attr('href', "/<%= @user.user_name %>/unfollow_user")
                   .attr('id', 'unfollow-button');

app/views/profiles/show.html.erb
<div class="posts-wrapper">
	<div class="row profile-header">
		<div class="col-md-6">
			<div class="img-md-6">
				<div class="img-circle">
					<%= profile_avatar_select(@user) %>
				</div>
			</div>
		</div>
		<div class="col-md-6">
			<div class="user-name-and-follow">
				<h3 class="profile-user-name">
					<%= @user.user_name %>
				</h3>
				<span>
					<%if @user == current_user %>
						<%= link_to 'Edit Profile', edit_profile_path(@user.user_name),
                                      class: 'btn edit-button' %>
          <% else %>
          	<% if current_user_is_following(current_user.id, @user.id)  %>
	          	<%= link_to 'Following', unfollow_user_path, remote: true,
	          														class: 'btn unfollow-button',
	          														id: 'unfollow-button',
	          														method: :post %>
	          <% else %>
	          	<%= link_to 'Follow', follow_user_path,
	          												remote: true,
	          												class: 'btn follow-button',
	          												id: 'follow-button',
	          												method: :post %>
	          <% end %>
					<% end %>
				</span>
			</div>
			<p class="profile-bio">
				<%= @user.bio %>
			</p>
			<div class="user-statistics">
				<p>
					<%= pluralize @user.posts.count, 'post' %>
				</p>
			</div>
		</div>
	</div>
</div>



<% if @user == current_user %>
	<%= link_to 'Edit Profile', edit_profile_path(@user.user_name) %>
<% end %>
<div class="posts-wrapper row">
	<% @posts.each do |post| %>
	<%= render 'posts/post', post: post %>
	<% end %>
</div>

app/views/profiles/unfollow_user.js.erb
$('#unfollow-button').text('Follow')
                     .attr('class', 'btn follow-button')
                     .attr('href', "/<%= @user.user_name %>/follow_user")
                     .attr('id', 'follow-button');

app/views/relationships/follow_user.html.erb
<h1>Relationships#follow_user</h1>
<p>Find me in app/views/relationships/follow_user.html.erb</p>

app/views/relationships/unfollow_user.html.erb
<h1>Relationships#unfollow_user</h1>
<p>Find me in app/views/relationships/unfollow_user.html.erb</p>